### ISSUE TITLE
Reescrever o Readme.md

### ISSUE THREAD

**Issue by caio-emidio** [aHub-Tech/hub-api#1]
Escrever sobre o projeto. Talvez pedir ajuda grumpy_lele.

**Comment by mateusdrag1** [comment]
<h1 align="center">
    HUB - API <br /><br />
    <img src="https://img.shields.io/github/contributors/aHub-Tech/hub-api.svg?style=for-the-badge"/>
    <img src="https://img.shields.io/github/forks/aHub-Tech/hub-api.svg?style=for-the-badge"/>
    <img src="https://img.shields.io/github/stars/aHub-Tech/hub-api.svg?style=for-the-badge"/>
    <img src="https://img.shields.io/github/issues/aHub-Tech/hub-api.svg?style=for-the-badge"/>
    <img src="https://img.shields.io/github/license/aHub-Tech/hub-api.svg?style=for-the-badge"/>
</h1>

  <h3 align="center">
     The Hub-API is a Backend developed for Hub Community on <a href="https://ahub.tech/discord">Discord</a> 🤖
    <br />
    <a href="https://ahub-api.herokuapp.com/">View Demo</a>
    ·
    <a href="https://github.com/aHub-Tech/hub-api/issues">Report Bug</a>
    ·
    <a href="https://github.com/aHub-Tech/hub-api/issues">Request Feature</a>
  </h3>

<h2 id="technologies"> 🛠 Technologies </h2>

- [TypeScript](https://www.typescriptlang.org/)
- [NestJS](https://nestjs.org/#/)
- [MongoDb](https://atlas.mongodb.com/)

<h2 id="usage" > 👷 How to install and Running the APP </h2>

```bash
# Clone the repository
$ git clone https://github.com/aHub-Tech/hub-api.git

# Going to project folder
$ cd hub-api

# Install all dependencies
$ npm install

# Start with development
$ npm run start

# Start in watch mode
$ npm run start:dev

# Start in production mode
$ npm run start:prod

# unit tests
$ npm run test

# e2e tests
$ npm run test:e2e

# test coverage
$ npm run test:cov
```

<h2 id="contribution"> 🤝 Contributors </h2>

<img src = "https://contrib.rocks/image?repo=aHub-Tech/hub-api"/>

<h2 id="license"> 📝 License </h2>

This project is licensed under the terms of the MIT license. View the file LICENSE for more details.

**Comment by caio-emidio** [comment]
Atualizado de acordo com o @mateusdrag1
