### ISSUE TITLE
Buscar em API da Twitch quem esta online

### ISSUE THREAD

**Issue by caio-emidio** [aHub-Tech/hub-api#14]
Precisamos saber quem esta online para poder mostrar isso na api - creators

**Comment by KlausEverWalkingDev** [comment]
Acho que esse link pode ajudar :)

=> https://dev.twitch.tv/docs/eventsub

**Comment by alissonsleal** [comment]
Acho que um webhook é meio overkill para esse caso.

Só fazer um GET para o `https://api.twitch.tv/kraken/streams/?channel${channelId}`, o único problema é que precisariamos fazer um outro request para pegar o channelId. Talvez seja uma boa ideia salvar o channelId de todos os creators em um json/db?

https://user-images.githubusercontent.com/19809377/122307113-14174e80-cee0-11eb-9837-c81eb0471ac2.mp4

**Comment by caio-emidio** [comment]
Vamos por o twitchId la no db vai dar boa 👍

**Comment by caio-emidio** [comment]
sinistro eh o tempo neh... 200ms pra cada streamer.

**Comment by alissonsleal** [comment]
Dá para passar todos os channelIds junto, parece que o tempo de resposta é quase o mesmo que passar só um.
Ex: `https://api.twitch.tv/kraken/streams/?channel=71092938,116885541`

docs: https://dev.twitch.tv/docs/v5/reference/streams

**Comment by caio-emidio** [comment]
Implementado.
