### ISSUE TITLE
Arquivar projeto?

### ISSUE THREAD

**Issue by RodrigoDornelles** [aHub-Tech/hub-api#24]
pelo que entendi esse projeto esta relacionado aos **creators** da hub, no qual não existe mais.

**Comment by caio-emidio** [comment]
na verdade nao.
a ideia desse projeto era servir tudo o q precisar de backend da hub. 
Um "middleware" - meio de campo real sobre as possiveis atividades.
Isso valia para creators/eventos/tutores e o q a gente venha a ter.

**Comment by caio-emidio** [comment]
acredito que o ideal agora eh dar um hold sobre arquivar ou nao. ate definir qual vai ser o backend do novo site da hub.

**Comment by caio-emidio** [comment]
Caso fique sob minha responsabilidade fazer o backend...
farei neste mesmo projeto. apenas modificando a parte de creators.
